---
- name: Stand up application container host
  hosts: web
  sudo: true
  user: ec2-user
  vars_files:
    - private/webapp-{{deploy_environment}}.yml
  pre_tasks:
    - name: Ensure docker is installed
      yum: name=docker state=latest
    - name: Ensure docker-py is installed
      yum: name=docker-python-1.0.0-53.el7.x86_64
    - name: Ensure docker is running and enabled
      service: name=docker state=started enabled=true
  post_tasks:
    - name: Remove unused docker containers
      shell: docker rm `docker ps -a -q`
      ignore_errors: yes
    - name: Remove unused docker images
      shell: docker rmi `docker images -q`
      ignore_errors: yes
  roles:
    - role: subscriber
